upstream back{
    server backend:8081;
}

server{

    listen 80;

    location /docs/ {
        alias /docs/;
    }

    location / {
        proxy_pass http://back;
        proxy_http_version 1.1;
    }
}