upstream back{
    server backend:8081;
}

server{

    listen 80;

    location /static/ {
        alias /static/;
    }

    location = /main {
        try_files /static/mainPage/index.html =404;
    }

    location = /tariffs {
        try_files /static/tariffs/index.html =404;
    }

    location = /faq {
        try_files /static/faq/index.html =404;
    }

    location = /complaints {
        try_files /static/complaints/index.html =404;
    }

    location / {
        proxy_pass http://back;
        proxy_http_version 1.1;
    }
}