upstream back{
    server backend:8081;
}

upstream calc{
    server calc:80;
}

server{

    listen 80;

    location /docs/ {
        alias /docs/;
    }

    location / {
        rewrite ^/(.*)/$ /$1 permanent;
        proxy_pass http://back;
        proxy_http_version 1.1;
    }

    location /api/gkh/ {
        proxy_pass http://calc/api/gkh/;
        proxy_http_version 1.1;
    }
}